name: mz_ls_refresher
description: A scrollView refresher package.
version: 0.0.4
author: Michael Zhou<zhoulujue@gmail.com>
homepage: https://github.com/zhoulujue/ls_refresher

environment:
  sdk: ">=2.0.0-dev.28.0 <3.0.0"
  flutter: ">=0.1.4 <2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter: